version: "3.8"

services:
  node-app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      - redis-server

  redis-server:
    image: redis:alpine
    ports:
      - "6379:6379" # Map Redis port to host